Reduce Go-WASM memory leak with TypedArrays. (#220)
1. Reuse Uint8Arrays to communicate with the Go process, since
inputs/outputs are never garbage-collected.

I believe this still has a tiny memory leak of the lengths passed back
and forth. This should be fixed by encoding the length into the
Uint8Array as well (either as a prefix or a NUL terminator).

2. Use https://github.com/termonio/wams to shrink the Go heap from 1G
to 768M. Shrinking it any more causes:

TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer

Perhaps under a memory crunch, the Go runtime moves things around to
defragment? I'm not really sure.

3. Add some skeletal support for Go 1.12, which will be changing the
JS->Go function call API.